# coding: utf-8

# flake8: noqa

"""
    CovA API

    Provides simple data about Covid19 // SpaceApps Hackathon 2020  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: tom@fjellsson.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.cov_a_user_api import CovAUserApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.evaluation import Evaluation
from swagger_client.models.logfile import Logfile
from swagger_client.models.weather import Weather
