# coding: utf-8

# flake8: noqa
"""
    CovA API

    Provides simple data about Covid19 // SpaceApps Hackathon 2020  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: tom@fjellsson.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.evaluation import Evaluation
from swagger_client.models.logfile import Logfile
from swagger_client.models.weather import Weather
