# coding: utf-8

"""
    CovA API

    Provides simple data about Covid19 // SpaceApps Hackathon 2020  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: tom@fjellsson.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Weather(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'temperature': 'int',
        'carbondioxide': 'int',
        'nitrogenoxide': 'int'
    }

    attribute_map = {
        'temperature': 'temperature',
        'carbondioxide': 'carbondioxide',
        'nitrogenoxide': 'nitrogenoxide'
    }

    def __init__(self, temperature=None, carbondioxide=None, nitrogenoxide=None):  # noqa: E501
        """Weather - a model defined in Swagger"""  # noqa: E501
        self._temperature = None
        self._carbondioxide = None
        self._nitrogenoxide = None
        self.discriminator = None
        self.temperature = temperature
        self.carbondioxide = carbondioxide
        self.nitrogenoxide = nitrogenoxide

    @property
    def temperature(self):
        """Gets the temperature of this Weather.  # noqa: E501


        :return: The temperature of this Weather.  # noqa: E501
        :rtype: int
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature):
        """Sets the temperature of this Weather.


        :param temperature: The temperature of this Weather.  # noqa: E501
        :type: int
        """
        if temperature is None:
            raise ValueError("Invalid value for `temperature`, must not be `None`")  # noqa: E501

        self._temperature = temperature

    @property
    def carbondioxide(self):
        """Gets the carbondioxide of this Weather.  # noqa: E501


        :return: The carbondioxide of this Weather.  # noqa: E501
        :rtype: int
        """
        return self._carbondioxide

    @carbondioxide.setter
    def carbondioxide(self, carbondioxide):
        """Sets the carbondioxide of this Weather.


        :param carbondioxide: The carbondioxide of this Weather.  # noqa: E501
        :type: int
        """
        if carbondioxide is None:
            raise ValueError("Invalid value for `carbondioxide`, must not be `None`")  # noqa: E501

        self._carbondioxide = carbondioxide

    @property
    def nitrogenoxide(self):
        """Gets the nitrogenoxide of this Weather.  # noqa: E501


        :return: The nitrogenoxide of this Weather.  # noqa: E501
        :rtype: int
        """
        return self._nitrogenoxide

    @nitrogenoxide.setter
    def nitrogenoxide(self, nitrogenoxide):
        """Sets the nitrogenoxide of this Weather.


        :param nitrogenoxide: The nitrogenoxide of this Weather.  # noqa: E501
        :type: int
        """
        if nitrogenoxide is None:
            raise ValueError("Invalid value for `nitrogenoxide`, must not be `None`")  # noqa: E501

        self._nitrogenoxide = nitrogenoxide

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Weather, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Weather):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
