# coding: utf-8

"""
    CovA API

    Provides simple data about Covid19 // SpaceApps Hackathon 2020  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: tom@fjellsson.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.logfile import Logfile  # noqa: E501
from swagger_client.rest import ApiException


class TestLogfile(unittest.TestCase):
    """Logfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLogfile(self):
        """Test Logfile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.logfile.Logfile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
